{
    "name":"JustSwap Default List",
    "tokens":[
        {
            "symbol":"SUN",
            "address":"TMEAzMAabRNaLYjF1KbBDmPEFdbnQUWpMH",
            "chainId":1,
            "decimals":18,
            "name":"SUN TOKEN",
            "logoURI":"https://coin.top/production/logo/SUNLogo.178d4636.png"
        },
        {
            "symbol":"BTC",
            "address":"bc1qcrmtwte0xd6mgn2g2upuraf373wmc0atcsfeey",
            "chainId":1,
            "decimals":8,
            "name":"Bitcoin",
            "logoURI":"https://coin.top/production/logo/bc1qcrmtwte0xd6mgn2g2upuraf373wmc0atcsfeey.png"
        },
        {
            "symbol":"WBTC",
            "address":"TDTcR8wBLadFYRekvobSSswHaj351EDNRT",
            "chainId":1,
            "decimals":8,
            "name":"Wrapped BTC",
            "logoURI":"https://coin.top/production/logo/TDTcR8wBLadFYRekvobSSswHaj351EDNRT.png"
        },
        {
            "symbol":"ETH",
            "address":"TJiriJZEWH1vz57oEEj2M35rcqmKaeWqqJ",
            "chainId":1,
            "decimals":18,
            "name":"Ethereum",
            "logoURI":"https://coin.top/production/logo/TJiriJZEWH1vz57oEEj2M35rcqmKaeWqqJ.png"
        },
        {
            "symbol":"WETH",
            "address":"TDTcR8wBLadFYRekvobSSswHaj351EDNRT",
            "chainId":1,
            "decimals":18,
            "name":"Wrapped ETH",
            "logoURI":"https://coin.top/production/logo/TDTcR8wBLadFYRekvobSSswHaj351EDNRT.png"
        },
        {
            "symbol":"WBTT",
            "address":"TDTcR8wBLadFYRekvobSSswHaj351EDNRT",
            "chainId":1,
            "decimals":6,
            "name":"Wrapped BitTorrent",
            "logoURI":"https://coin.top/production/logo/TDTcR8wBLadFYRekvobSSswHaj351EDNRT.png"
        },
        {
            "symbol":"WTRX",
            "address":"TDTcR8wBLadFYRekvobSSswHaj351EDNRT",
            "chainId":1,
            "decimals":6,
            "name":"Wrapped TRX",
            "logoURI":"https://coin.top/production/upload/logo/TDTcR8wBLadFYRekvobSSswHaj351EDNRT.png"
        },
        {
            "symbol":"JST",
            "address":"bc1qcrmtwte0xd6mgn2g2upuraf373wmc0atcsfeey",
            "chainId":1,
            "decimals":18,
            "name":"JUST GOV v1.0",
            "logoURI":"https://coin.top/production/logo/just_icon.png"
        },
        {
            "symbol":"WIN",
            "address":"bc1qcrmtwte0xd6mgn2g2upuraf373wmc0atcsfeey",
            "chainId":1,
            "decimals":6,
            "name":"WINK",
            "logoURI":"https://coin.top/profile_images/JKtJTydD_400x400.jpg"
        },
        {
            "symbol":"DICE",
            "address":"TDTcR8wBLadFYRekvobSSswHaj351EDNRT",
            "chainId":1,
            "decimals":6,
            "name":"TRONbetDice",
            "logoURI":"https://coin.top/production/logo/TDTcR8wBLadFYRekvobSSswHaj351EDNRT.jpg"
        },
        {
            "symbol":"LIVE",
            "address":"TMEAzMAabRNaLYjF1KbBDmPEFdbnQUWpMH",
            "chainId":1,
            "decimals":6,
            "name":"TRONbetLive",
            "logoURI":"https://coin.top/production/upload/logo/TMEAzMAabRNaLYjF1KbBDmPEFdbnQUWpMH.png"
        },
        {
            "symbol":"USDT",
            "address":"TNcJX95T6wrdYP1418Enb32j32ae9wjuXB",
            "chainId":1,
            "decimals":6,
            "name":"Tether USD",
            "logoURI":"https://coin.top/production/logo/usdtlogo.png"
        },
        {
            "symbol":"USDJ",
            "address":"TMEAzMAabRNaLYjF1KbBDmPEFdbnQUWpMH",
            "chainId":1,
            "decimals":18,
            "name":"JUST Stablecoin v1.0",
            "logoURI":"https://coin.top/production/logo/usdj.png"
        },
        {
            "symbol":"LTC",
            "address":"TDTcR8wBLadFYRekvobSSswHaj351EDNRT",
            "chainId":1,
            "decimals":8,
            "name":"Litecoin",
            "logoURI":"https://coin.top/production/logo/TDTcR8wBLadFYRekvobSSswHaj351EDNRT.png"
        },
        {
            "symbol":"HT",
            "address":"TDTcR8wBLadFYRekvobSSswHaj351EDNRT",
            "chainId":1,
            "decimals":18,
            "name":"HuobiToken",
            "logoURI":"https://coin.top/production/logo/TDTcR8wBLadFYRekvobSSswHaj351EDNRT.png"
        }
    ],
    "logoURI":"https://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1611147166000
}
